variables:
  SCS_VERSION: "1.2"

stages:
  - build
  - deploy

build_image:
   stage: build
   tags:
    - dind
   script:
     - echo docker build -t $CI_PROJECT_NAME:review_$SCS_VERSION -f docker/Dockerfile .
     - docker build -t $CI_PROJECT_NAME:review_$SCS_VERSION -f docker/Dockerfile .
   except:
     - master
     
deploy_review::
   stage: deploy
   variables:
    GIT_STRATEGY: none
   environment:
    name: review/$CI_PROJECT_NAME.$SCS_VERSION.$GITLAB_USER_LOGIN
    url: https://review.scsuk.net
   tags:
    - dind
   script:
     - docker container stop scs_review
     - docker container rm scs_review
     - echo docker run -d --name=scs_review --network=jamnet $CI_PROJECT_NAME:review_$SCS_VERSION
     - docker run -d --name=scs_review --network=jamnet $CI_PROJECT_NAME:review_$SCS_VERSION
   except:
     - master

deploy_prod:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - dind
  script:
    - echo docker tag $CI_PROJECT_NAME:review_$SCS_VERSION $CI_PROJECT_NAME:$SCS_VERSION
    - docker tag $CI_PROJECT_NAME:review_$SCS_VERSION $CI_PROJECT_NAME:$SCS_VERSION
    - echo docker rmi $CI_PROJECT_NAME:review_$SCS_VERSION
    - docker rmi $CI_PROJECT_NAME:review_$SCS_VERSION
    - docker stop knocat
    - docker rm knocat
    - >
       echo docker run -d --name=knocat --network=jamnet --hostname=knocat --restart=always 
       --volume knocat_html:/var/www/html 
       --volume knocat_cgi-bin:/var/www/cgi-bin 
       --volume knocat_logs:/var/log/httpd 
       --volume knocat_conf:/etc/httpd 
       $CI_PROJECT_NAME:$SCS_VERSION
    - >
       docker run -d --name=knocat --network=jamnet --hostname=knocat --restart=always 
       --volume knocat_html:/var/www/html 
       --volume knocat_cgi-bin:/var/www/cgi-bin 
       --volume knocat_logs:/var/log/httpd 
       --volume knocat_conf:/etc/httpd 
       $CI_PROJECT_NAME:$SCS_VERSION
  environment:
    name: production
    url: https://www.knocat.com
  when: manual
  only:
  - master
