variables:
  SCS_VERSION: "1.4"

stages:
  - build
  - deploy

build_image:
   stage: build
   tags:
    - dind
   script:
     - docker build -t $CI_PROJECT_NAME:review_$SCS_VERSION -f docker/Dockerfile .
   except:
     - master
     
deploy_review::
   stage: deploy
   variables:
    GIT_STRATEGY: none
   environment:
    name: review/$CI_PROJECT_NAME.$SCS_VERSION.$GITLAB_USER_LOGIN
    url: https://review.scsuk.net
   tags:
    - dind
   script:
     - docker container stop scs_review || echo "Continue"
     - docker container rm scs_review || echo "Continue"
     - docker run -d --name=scs_review --network=jamnet $CI_PROJECT_NAME:review_$SCS_VERSION
   except:
     - master

deploy_prod:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - dind
  script:
    - docker tag $CI_PROJECT_NAME:review_$SCS_VERSION $CI_PROJECT_NAME:$SCS_VERSION
    - docker rmi $CI_PROJECT_NAME:review_$SCS_VERSION
    - docker stop knocat || echo "Continue"
    - docker rm knocat || echo "Continue"
    - >
       docker run -d --name=knocat --network=jamnet --hostname=knocat --restart=always 
       --volume knocat_html:/var/www/html 
       --volume knocat_cgi-bin:/var/www/cgi-bin 
       --volume knocat_logs:/var/log/httpd 
       --volume knocat_conf:/etc/httpd 
       $CI_PROJECT_NAME:$SCS_VERSION
    - docker container stop scs_review || echo "Continue"
    - docker container rm scs_review || echo "Continue"
  environment:
    name: production
    url: https://www.knocat.com
  when: manual
  only:
  - master
