stages:
  - build
  - deploy

build_image:
   stage: build
   tags:
    - dind
   script:
     - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME -f docker/Dockerfile .
     
deploy_review::
   stage: deploy
   environment:
    name: review/$CI_PROJECT_NAME.$CI_COMMIT_REF_NAME
    url: https://review.scsuk.net
   tags:
    - dind
   script:
     - docker volume create knocat_html_$CI_COMMIT_REF_NAME 
     - docker run -d --name=scs_review --network=jamnet  --hostname=knocat_$CI_COMMIT_REF_NAME --restart=always --volume knocat_html_$CI_COMMIT_REF_NAME:/var/www/html $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME

deploy_prod:
  stage: deploy
  script:
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME $CI_PROJECT_NAME:latest
  environment:
    name: production
    url: https://www.knocat.com
  when: manual
  only:
  - master
