variables:
  SCS_VERSION: "1.15"

stages:
  - build
  - deploy

build_image:
   stage: build
   tags:
    - dind
   script:
     - echo "Build the image $CI_PROJECT_NAME:review_$SCS_VERSION"
     - docker build -t $CI_PROJECT_NAME:review_$SCS_VERSION -f docker/Dockerfile .
   except:
     - master
     
deploy_review:
   stage: deploy
   variables:
    GIT_STRATEGY: none
   environment:
    name: review/$CI_PROJECT_NAME.$SCS_VERSION.$GITLAB_USER_LOGIN
    url: https://review.scsuk.net
    on_stop: stop_review
   tags:
    - dind
   script:
     - echo "Stop and remove the review container if running/exists"
     - docker container stop scs_review || echo "Container not running"
     - docker container rm scs_review || echo "Container does not exist"
     - echo "Start the review container"
     - docker run -d --name=scs_review --network=jamnet $CI_PROJECT_NAME:review_$SCS_VERSION
   except:
     - master

stop_review:
  tags:
    - dind
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review container"
    - docker container stop scs_review || echo "Container not running"
    - docker container rm scs_review || echo "Container does not exist"
  when: manual
  environment:
    name: review/$CI_PROJECT_NAME.$SCS_VERSION.$GITLAB_USER_LOGIN
    action: stop

deploy_prod:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - dind
  script:
    - echo "Change review tag to versioned production tag"
    - docker tag $CI_PROJECT_NAME:review_$SCS_VERSION $CI_PROJECT_NAME:$SCS_VERSION
    - docker rmi $CI_PROJECT_NAME:review_$SCS_VERSION
    - echo "Stop and remove the currnet production container"
    - docker stop knocat || echo "Continue"
    - docker rm knocat || echo "Continue"
    - echo "Create a new production container based on the new image"
    - >
       docker run -d --name=knocat --network=jamnet --hostname=knocat --restart=always 
       --volume knocat_logs:/var/log/httpd 
       $CI_PROJECT_NAME:$SCS_VERSION
  environment:
    name: production
    url: https://www.knocat.com
  when: manual
  only:
  - master
